name: integracion continua

on:
  pull_request:
    branches: [ master ]

jobs:
  py_to_master:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - run: python -m pip install --upgrade pip
      - run: python -m unittest Unittest/test_something.py -v